config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :tweets do
    resources :comments
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'tweets#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true, length: { maximum: 140 }
  belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :body, presence: true, length: { maximum: 140 }

  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar
  has_many :tweets, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @tweet = Tweet.find(params[:tweet_id])
    @comment = @tweet.comments.create(comment_params)
    redirect_to tweet_path(@tweet)
  end

  def destroy
    @tweet = Tweet.find(params[:tweet_id])
    @comment = @tweet.comments.find(params[:id])
    @comment.destroy
    redirect_to tweet_path(@tweet)
  end

  private

  def comment_params
    hash_comments = params.require(:comment).permit(:body)
    hash_comments[:user_id] = current_user.id
    hash_comments
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:name, :username, :email,
                                 :avatar, :password,
                                 :password_confirmation)
  end

  def acount_update_params
    params.require(:user).permit(:name, :username, :email,
                                 :avatar, :password,
                                 :password_confirmation,
                                 :current_password)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]

  # GET /tweets or /tweets.json
  def index
    @tweets = Tweet.all.order('created_at DESC')
    @tweet = Tweet.new
  end

  # GET /tweets/1 or /tweets/1.json
  def show; end

  # GET /tweets/new
  def new
    @tweet = current_user.tweets.build
  end

  # GET /tweets/1/edit
  def edit; end

  # POST /tweets or /tweets.json
  def create
    @tweet = current_user.tweets.build(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to root_path, notice: 'Tweet was successfully created.' }
      else
        format.html { redirect_to root_path, alert: 'Tweet is over 140 characters.' }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to root_path, notice: 'Tweet was successfully updated.' }
      else
        format.html { redirect_to root_path, alert: 'Tweet is over 140 characters.' }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy
    redirect_to tweets_url, flash: { notice: 'Tweet was successfully destroyed' }
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def tweet_params
    params.require(:tweet).permit(:body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/comments/_comment.html.erb
<div class="box">
  <article class="media">
    <div class="media-left">
      <figure class="image">
        <% if User.all.find_by(id: comment.user_id).avatar.attached? %>
        <%= image_tag User.all.find_by(id: comment.user_id).avatar, class: "avatar-img"%>
      <% else %>
        <%= image_tag "avatar.svg", alt: "user_defect", class: "avatar-img"%>
      <% end %>
      </figure>
    </div>
    <div class="media-content">
      <div class="content">
        <strong><%= User.all.find_by(id: comment.user_id).name %></strong>
        <small>@<%= User.all.find_by(id: comment.user_id).username %></small><br/>
        <p><%= comment.body %></p>
      </div>
      <nav class="level">
				<div class="level-left is-mobile">
          <% if user_signed_in? && current_user.id == comment.user_id %>
          <nav class="level">
            <div class="level-left is-mobile">
    
              <%= link_to [comment.tweet,comment], method: :delete, data: { confirm: "Are you sure you want to delete this comment?" } do %>
                  <span class="icon"><i class="fa fa-trash-o" aria-hidden="true"></i></span>
              <% end %>
            </div>
          </nav>
          <% end %>
        </div>
      </nav>
    </div>
  </article>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for([@tweet, @tweet.comments.build]) do |f| %>
<%= f.error_notification %>
<div class="field">
  <div class="control">
    <%= f.input :body, label: false, input_html: { class: "textarea "}, wrapper: false, label_html: {class: "label"}, placeholder: "Remember to thing before write...", autofocus: true %>
  </div>
</div>
<%= f.button :submit, class: "button is-info" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tweetable</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
  </head>

  <body>
  	<nav class="navbar is-info">
  		<div class="navbar-brand">
  		<%= link_to root_path, class: "navbar-item" do %>
  			<h1 class="title is-5">Tweetable</h1>
  		<% end %>
			<div class="navbar-burger burger" data-target="navbarExample">
				<span aria-hidden="true"></span>
				<span aria-hidden="true"></span>
				<span aria-hidden="true"></span>
  		</div>
  	 </div>

			<div id="navbarExample" class="navbar-menu">
				<div class="navbar-end">
          <div class="navbar-item">
					<div class="field is-grouped">
						<p class="control">
							<%= link_to 'New Tweet', root_path, class: "button is-info is-inverted" %>
						</p>
            <% if user_signed_in? %>
              <p class="control">
                <%= link_to current_user.name, edit_user_registration_path, class: "button is-info" %>
              </p>
              <p>
                <%= link_to "Logout", destroy_user_session_path, method: :delete, class:"button is-info" %>
              </p>
            <% else %>
            <p class="control">
              <%= link_to 'Sign In', new_user_session_path, class: "button is-info" %>
            </p>
						<p class="control">
              <%= link_to 'Sign Up', new_user_registration_path, class: "button is-info" %>
            </p>
            <% end %>
            </div>
					</div>
				</div>
			</div>
  	</nav>
		<% if flash[:notice] -%>
		<div class = "message is-link flash-card"><%= flash[:notice] %>
		</div>
	<% end %>
  	<% if flash[:alert] %>
  		<div class="message is-danger flash-card">
  			<p class="alert"><%= alert %></p>
  		</div>
  	<% end %>
    <%= yield %>
  </body>
</html>

app/views/tweets/_feed.html.erb
<div class="column is-half">
  <% if user_signed_in? %>
  <article class="media box">
    <figure class="media-left">
      <p class="image is-64x64">
        <% if current_user.nil? %>
        <%= image_tag "avatar.svg", alt: "user_defect", class: "avatar-img"%>
      <% else %>
        <% if current_user.avatar.attached? %>
          <%= image_tag current_user.avatar, class: "avatar-img"%>
        <% else %>
          <%= image_tag "avatar.svg", alt: "user_defect", class: "avatar-img"%>
        <% end %>
      <% end %>
      </p>
    </figure>
    <div class="media-content">
      <%= render 'tweets/form' %>
    </div>
  </article>
  <% end %>

<% @tweets.each do |tweet| %>
  <div class="box">
    <article class="media">
      <div class="media-left">
        <figure class="image">
          <%= image_tag tweet.user.avatar, class: "avatar-img"%>
        </figure>
      </div>
      <div class="media-content">
        <div class="content">
          <strong><%= tweet.user.name %></strong>
          <small>@<%= tweet.user.username %></small><br/>
          <p class = "subtitle is-6"><%= tweet.body %></p>
        </div>
        <nav class="level">
  				<div class="level-left is-mobile">

            <nav class="level">
              <div class="level-left is-mobile">
                <%= link_to tweet, class: "level-item" do %>
                  <span class="icon"><i class="fa fa-comment" aria-hidden="true"></i></span>
                  <span class="icon"><%=tweet.comments.count%></span>
                <% end %>
                <% if user_signed_in? && current_user.id == tweet.user_id %>
                <%= link_to edit_tweet_path(tweet), class: "level-item" do %>
                  <span class="icon"><i class="fa fa-pencil" aria-hidden="true"></i></span>
                <% end %>
                <%= link_to tweet, method: :delete, data: { confirm: "Are you sure you want to delete this tweet?" } do %>
                    <span class="icon"><i class="fa fa-trash-o" aria-hidden="true"></i></span>
                <% end %>
              </div>
            </nav>
            <% end %>
          </div>
        </nav>
      </div>
    </article>
  </div>
<% end %>
</div>

app/views/tweets/_form.html.erb
<%= simple_form_for(@tweet) do |f| %>
<%= f.error_notification %>
<div class="field">
  <div class="control">
    <%= f.input :body, label: false, input_html: { class: "textarea"}, wrapper: false, label_html: {class: "label"}, placeholder: "Remember to thing before write...", autofocus: true %>
  </div>
</div>
<%= f.button :submit, class: "button is-info" %>
<% end %>

app/views/tweets/_profile.html.erb
<div class="column is-one-quarter">
	<nav class="panel">
		<% if current_user.nil? %>
		<p class="panel-heading">You are not logged in</p>
		<div class="panel-block">
			<article class="media">
				<div class="media-content">
					<div class="content">
						<p>
							<strong>What are you waiting to do it?</strong><br />
						</p>
					</div>
				</div>
			</article>
		</div>
		<% else %>
		<p class="panel-heading">Profile</p>
		<div class="panel-block">
			<article class="media">
				<div class="media-left">
					<figure class="image is-64x64">
							<% if current_user.avatar.attached? %>
								<%= image_tag current_user.avatar, class: "avatar-img"%>
							<% else %>
								<%= image_tag "avatar.svg", alt: "user_defect", class: "avatar-img"%>
						<% end %>
					</figure>
				</div>
				<div class="media-content">
					<div class="content">
						<p>
							<strong><%= current_user.name %></strong><br />
							<small><%= current_user.username %></small>
						</p>
					</div>
				</div>
			</article>
		</div>
		<div class="panel-block">
			<div class="level is-mobile">
				<div class="level-item has-centered-text">
					<div>
						<p class="heading">Tweets</p>
						<p class="title is-6"><%= current_user.tweets.count %></p>
					</div>
				</div>
			</div>
		</div>
	</nav>
	<% end %>
</div>

app/views/tweets/_users.html.erb
<div class="column">
	<nav class="panel">
		<p class="panel-heading">Users</p>
	<% User.all.each do |user| %>
	<div class="panel-block">
		<article class="media">
			<div class="media-left">
				<figure class="image avatar-img--25">
          <%= image_tag user.avatar, class: "avatar-img--25"%>
				</figure>
			</div>
			<div class="media-content">
				<div class="content">
					<p>
						<strong><%= user.name %></strong>
						<small>@<%= user.username %></small>
					</p>
				</div>
			</div>
		</article>
	</div>
	<% end %>
	</nav>
</div>

app/views/tweets/edit.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">Editing Tweet</h1>
				<%= render 'form', tweet: @tweet %>
			</div>
		</div>
	</div>
</div>

<nav class="navbar is-fixed-bottom">
	<div class="navbar-menu">
		<div class="navbar-item">
			<div class="field is-grouped">
				<p class="control">
					<%= link_to 'Cancel', tweets_path, class: "button is-dark" %>
				</p>
		</div>
	</div>
</nav>

app/views/tweets/index.html.erb
<section class = "section">
  <div class = "container">
    <div class = "columns">

      <%= render 'profile' %> 

      <%= render 'feed' %>

      <%= render 'users' %>

    </div>
  </div>
</section>

app/views/tweets/new.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">Create a new Tweet</h1>
					<%= render 'form', tweet: @tweet %>
			</div>
		</div>
	</div>
</div>

<nav class="navbar is-fixed-bottom">
	<div class="navbar-menu">
		<div class="navbar-item">
			<div class="field is-grouped">
				<p class="control">
					<%= link_to 'Cancel', tweets_path, class: "button is-dark" %>
				</p>
		</div>
	</div>
</nav>

app/views/tweets/show.html.erb
<div class="box">
  <article class="media">
    <div class="media-left">
      <figure class="image">
        <%= image_tag @tweet.user.avatar, class: "avatar-img"%>
      </figure>
    </div>
    <div class="media-content">
      <div class="content">
        <strong><%= @tweet.user.name %></strong>
        <small>@<%= @tweet.user.username %></small><br/>
        <p><%= @tweet.body %></p>
      </div>
      <nav class="level">
        <div class="level-left is-mobile">
          <% if user_signed_in? && current_user.id == @tweet.user_id %>
          <nav class="level">
            <div class="level-left is-mobile">
              <%= link_to @tweet, class: "level-item" do %>
                <span class="icon"><i class="fa fa-comment" aria-hidden="true"></i></span>
              <% end %>
              <%= link_to edit_tweet_path(@tweet), class: "level-item" do %>
                <span class="icon"><i class="fa fa-pencil" aria-hidden="true"></i></span>
              <% end %>
              <%= link_to @tweet, method: :delete, data: { confirm: "Are you sure you want to delete this tweet?" } do %>
                  <span class="icon"><i class="fa fa-trash-o" aria-hidden="true"></i></span>
              <% end %>
            </div>
          </nav>
          <% end %>
        </div>
      </nav>
    </div>
  </article>
</div>
<div class="order--coments">
  <%= render @tweet.comments %>
  <% if user_signed_in? %>
  <%= render 'comments/form' %>
  <% end %>
</div>